server:
  port: 2023

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jay
    password: jay
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect